version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mydb
      - SECRET=40TJXuVtRuDscAPosxe1GXulw5+ZZbIcubG5jf6CbGo0
      - END=30d
      - NODE_ENV=development
      - PORT=8000
      - REDIS_URL=redis://redis:6379
      - ORIGIN="http://localhost:3000"
    volumes:
      - ./server:/server

  app:
    build: ./next-app
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - server
    environment:
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mydb
    volumes:
      - .:/app

volumes:
  db:
