version: "3.8"

services:
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis_data:/data

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db:
