import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import TopLoader from "@/components/TopLoader";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <Toaster
            position="top-right"
            toastOptions={{
              success: {
                style: {
                  background: "white",
                  fontWeight: "bold",
                  textTransform: "capitalize",
                },
              },
              error: {
                style: {
                  background: "white",
                  fontWeight: "bold",
                  textTransform: "capitalize",
                },
              },
            }}
          />
          <TopLoader />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
